name: 'rcmdcheck'

on: [push, pull_request]

env:
  cache-version: v1

# source: https://github.com/seandavi/BuildABiocWorkshop

jobs:
  r-check:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Query dependencies and update old packages
        run: |
          BiocManager::install(ask=FALSE)
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}
        
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: /usr/local/lib/R/site-library
          key: ${{ env.cache-version }}-${{ runner.os }}-r-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ env.cache-version }}-${{ runner.os }}-r-

      # This lets us augment with additional dependencies
      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          remotes::install_cran('Seurat')
        shell: Rscript {0}
      
      - name: Install dependencies
        run: |
          options(repos = c(CRAN = "https://cran.r-project.org"))
          BiocManager::repositories()
          remotes::install_deps(dependencies = TRUE, repos = BiocManager::repositories())
          remotes::install_cran("rcmdcheck")
          remotes::install_bioc("BiocCheck")
        shell: Rscript {0}

      - name: rcmdcheck
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--no-examples"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: BiocCheck
        run: BiocCheck::BiocCheck()
        shell: Rscript {0}
